#!/usr/bin/env python3
"""Generate matching offline Android/iOS location lists from the shared catalogue.

Run with --check to validate coordinates/provenance and detect platform drift
without changing files. The catalogue's published coordinates are planning
references, not verified fishing access points or launch facilities.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
CATALOGUE = ROOT / "data/fishing_locations.json"
ANDROID = ROOT / "app/src/main/java/nz/fishingnz/app/model/Models.kt"
IOS = ROOT / "iosApp/CatchCheckNZ/Services/FishingScoringService.swift"
START = "// BEGIN GENERATED FISHING LOCATIONS"
END = "// END GENERATED FISHING LOCATIONS"


def validate(catalogue: dict) -> list[dict]:
    if catalogue.get("schema_version") != 1:
        raise ValueError("Unsupported fishing-location schema")
    locations = catalogue["locations"]
    if not locations:
        raise ValueError("Fishing-location catalogue is empty")
    ids, identities, map_keys = set(), set(), set()
    kinds = {"legacy_approximate", "linz_gazetteer", "linz_tide_reference", "doc_coastal_access"}
    for location in locations:
        for field in ("id", "name", "area", "coordinate_note"):
            if not isinstance(location.get(field), str) or not location[field].strip():
                raise ValueError(f"Missing {field}: {location}")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", location["id"]):
            raise ValueError(f"Invalid location id: {location['id']}")
        for field, minimum, maximum in (("latitude", -48, -34), ("longitude", 166, 179)):
            value = location.get(field)
            if type(value) not in (int, float) or not math.isfinite(value) or not minimum <= value <= maximum:
                raise ValueError(f"Invalid mainland NZ {field}: {location['name']}")
        if type(location.get("boat")) is not bool:
            raise ValueError(f"Invalid fishing type: {location['name']}")
        identity = (location["name"].casefold(), location["boat"])
        map_key = (location["name"], location["latitude"], location["longitude"])
        if location["id"] in ids or identity in identities or map_key in map_keys:
            raise ValueError(f"Duplicate fishing location/map key: {location['name']}")
        ids.add(location["id"])
        identities.add(identity)
        map_keys.add(map_key)
        kind = location.get("source_kind")
        if kind not in kinds or not isinstance(location.get("source_urls"), list):
            raise ValueError(f"Invalid coordinate provenance: {location['name']}")
        if kind != "legacy_approximate" and (not location["source_urls"] or not location.get("reviewed_on")):
            raise ValueError(f"Published coordinate needs a source and review date: {location['name']}")
        for url in location["source_urls"]:
            parsed = urlsplit(url)
            if parsed.scheme != "https" or parsed.hostname not in {
                "gazetteer.linz.govt.nz", "static.charts.linz.govt.nz", "www.doc.govt.nz"
            }:
                raise ValueError(f"Unexpected location source: {url}")
        if kind == "linz_gazetteer" and location.get("source_feature_type") not in {
            "Beach", "Bay", "Point", "Recreation Reserve"
        }:
            raise ValueError(f"Gazetteer feature is not a coastal reference: {location['name']}")
    return locations


def string(value: str, kotlin: bool = False) -> str:
    result = json.dumps(value, ensure_ascii=False)
    return result.replace("$", "\\$") if kotlin else result


def generated_block(locations: list[dict], kotlin: bool) -> str:
    header = [START,
              "// Generated by tools/sync_fishing_locations.py from data/fishing_locations.json.",
              "// Published coordinate sources and approximate legacy entries are recorded in that catalogue.",
              "// Pins identify coastal planning areas; check local access and fishing restrictions."]
    if kotlin:
        lines = [f"    FishingSpot({string(s['name'], True)}, {string(s['area'], True)}, {s['latitude']}, {s['longitude']}, {str(s['boat']).lower()})" for s in locations]
        declaration, closing = "val fishingSpots = listOf(", ")"
    else:
        lines = [f"    .init(name: {string(s['name'])}, area: {string(s['area'])}, coordinate: .init(latitude: {s['latitude']}, longitude: {s['longitude']}), boat: {str(s['boat']).lower()})" for s in locations]
        declaration, closing = "let fishingSpots: [FishingSpot] = [", "]"
    return "\n".join(header + [declaration, ",\n".join(lines), closing, END])


def update(path: Path, block: str, check: bool) -> bool:
    current = path.read_text()
    if START in current:
        pattern = re.escape(START) + r".*?" + re.escape(END)
    elif path == ANDROID:
        pattern = r"// Named coastal search points\..*?\nval fishingSpots = listOf\(.*?\n\)"
    else:
        pattern = r"// Curated named coastal areas\..*?\nlet fishingSpots: \[FishingSpot\] = \[.*?\n\]"
    updated, count = re.subn(pattern, lambda _: block, current, flags=re.DOTALL)
    if count != 1:
        raise ValueError(f"Expected exactly one fishing-location list in {path}")
    if updated == current:
        return True
    if check:
        print(f"Location list differs from shared catalogue: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.write_text(updated)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate and compare without writing")
    args = parser.parse_args()
    try:
        locations = validate(json.loads(CATALOGUE.read_text()))
        android = update(ANDROID, generated_block(locations, True), args.check)
        ios = update(IOS, generated_block(locations, False), args.check)
        if not (android and ios):
            return 1
        land = sum(not s["boat"] for s in locations)
        print(f"{'Verified' if args.check else 'Synced'} {len(locations)} locations: {land} land, {len(locations) - land} boat; Android and iOS match.")
        return 0
    except (KeyError, ValueError, TypeError) as error:
        print(f"Invalid fishing-location catalogue: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
